/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.example.view.SomeView;

import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

// See https://fxdocs.github.io/docs/html5/#_the_mvvm_pattern
public class App extends Application {

    private Parent createContent() {
        return new SomeView();
    }

    @Override
    public void start(Stage stage) throws Exception {
        stage.setScene(new Scene(createContent(), 300, 300));
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }

}
